apiVersion: v1
appVersion: 3.141.59
#deprecated: true
description: DEPRECATED - Chart for selenium grid
home: http://www.seleniumhq.org/
icon: http://docs.seleniumhq.org/images/big-logo.png
keywords:
- qa
name: selenium
sources:
- https://github.com/SeleniumHQ/docker-selenium
version: 1.2.3
